### ISSUE TITLE
Type checking

### ISSUE THREAD

**Issue by cca-bheath** [JoggApp/laravel-mail-viewer#13]
You are making the assumption that all parameters in the Mailable have type hints.  Which isn't a good assumption.  Thus people like myself get a `Call to a member function getName() on null` on

```php
$constructorParameters[] = $parameter->getType()->getName() == 'int' ? 'integer' : $parameter->getType()->getName();
```

Could this be changed to check for getType() and if there then compare it against that match in the constructorParameters and if not assume that it's valid.

**Comment by introwit** [comment]
Hi Bryan 🙂 

In this specific package context, I believe one should typehint the constructor dependencies, reasons:

- It allows for better readability and makes error control and strict programming conventions easier to apply
- Type hinting is very helpful in the code that is opensource or opensource dependent, since assumptions are included then and typehinting helps in tackling them.
- In this specific context, there is also an extra step that would need to be taken which is: adding extra logic to resolve those *non-typehinted* values, which is unnecessary.

**Comment by cca-bheath** [comment]
I agree with you on your points.  However, you want to do it in your package is totally your call.  

The problem as I see it is that type hinting is not a standard.  Much of Laravel package method parameters are not type hinted.  

Also what if someone used args for example?

It wouldn't take much of a change to accomplish this.  I will make the PR if you want.

If you don't want it then that's fine.  Just trying to make a case.
